language: node_js
node_js:
  - "4"
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - npm install
before_script:
  - npm run lint-server
  - npm run lint-client
  - npm run build-server
  - npm run build-client
  - npm run test-server
  - npm run test-client